version: '3'
services:
  nginx:
    image: nginx:1.17.2
    container_name: nginx
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - hplus
    volumes:
      - ./webapp/load_balance_nginx.conf:/etc/nginx/conf.d/hplus.conf
  hplus1:
    image: michaelbjames/hoogleplus_web:latest
    container_name: hplus1
    networks:
      - hplus
    volumes:
      - ./logs/1/:/var/log/hplus/
  hplus2:
    image: michaelbjames/hoogleplus_web:latest
    container_name: hplus2
    networks:
      - hplus
    volumes:
      - ./logs/2/:/var/log/hplus/
  hplus3:
    image: michaelbjames/hoogleplus_web:latest
    container_name: hplus4
    networks:
      - hplus
    volumes:
      - ./logs/3/:/var/log/hplus/
  hplus4:
    image: michaelbjames/hoogleplus_web:latest
    container_name: hplus4
    networks:
      - hplus
    volumes:
      - ./logs/4/:/var/log/hplus/

networks:
  hplus:
