route: /search/type
method: POST
args: {
    "typeSignature": str,
    "facts": [
        [str] # (num of args + 1)
        ]
    }
returns:
    {
        "id": uuid-str
        "results": [
            {
                "candidate": ast,
                "examples": [{inputs: [str], output: str}]
            }
        ]
    }

route: /search/example
method: POST
args: {
    "facts": [
        [str] # (num of args + 1)
        ]
    }
returns:
    { "typeCandidates": [str] }

route: /stop
method: POST
args: {"id": uuid}
returns: None

route: /examples
method: POST
args: {
    "typeSignature": str,
    "candidate": str,
    "examples": [[str]]
    }
returns: {
    "examples": [{inputs: [str], output: str}]
    }

route: /example/code
method: POST
args: {
    "typeSignature": str,
    "candidate": str,
    "args": [str]
}
returns: {
    "result": str,
    "error": str
}


route: /typecheck
method: POST
args: {
    "typeName": str,
    "term": str
}
returns: {
    "result": "ok",
    "error": str
}